version: "3"

services:
  server:
    build: ./Back
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
    env_file:
      - ./.env
    depends_on:
      - mongodb
  client:
    build: ./Front
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ./data:/data/db
    restart: always
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
  query-redis-srv:
    image: redis
volumes:
  web-client-build:
