export const allMoods = [
    {
        _id: '6096bf96ab2e797b569f4182',
        title: 'mySadMood',
        image: 'https://openmoji.org/data/color/svg/1F612.svg',
    },
    {
        _id: '6096bf9fab2e797b569f4183',
        title: 'myGoodMood',
        image: 'https://openmoji.org/data/color/svg/1F604.svg',
    },
    {
        _id: '60af7f89d17994f991c5afc3',
        title: 'myNeutralMood',
        image: 'https://openmoji.org/data/color/svg/1F610.svg',
    },
] as const;
export type AllMoods = typeof allMoods[number]['image'];

export const allHobbies = [
    'aperitif',
    'art',
    'circus arts',
    'martial arts',
    'astrology',
    'astronomy',
    'basketball',
    'bilboquet',
    'singing',
    'cinema',
    'concerts',
    'running',
    'sewing',
    'cooking',
    'dancing',
    'drawing',
    'personal development',
    'chess',
    'ecology',
    'writing',
    'horse riding',
    'rock climbing',
    'festivals',
    'film',
    'fitness',
    'football',
    'golf',
    'computers',
    'gardening',
    'board games',
    'video games',
    'kayaking',
    'reading',
    'mixology',
    'weight training',
    'music',
    'meditation',
    'swimming',
    'netflix',
    'paintball',
    'painting',
    'photography',
    'diving',
    'pottery - ceramics',
    'poetry',
    'pastry',
    'fishing',
    'hiking',
    'skateboarding',
    'snow / ski',
    'television sport',
    'sports',
    'surfing',
    'series',
    'tennis',
    'theatre / improvisation',
    'archery',
    'knitting',
    'sailing',
    'volunteering',
    'travel',
    'cycling',
    'web',
    'yoga',
] as const;
export type AllHobbies = typeof allHobbies[number];
