export const allMoods = [
    {
        _id: '6096bf96ab2e797b569f4182',
        title: 'mySadMood',
        image: 'https://openmoji.org/data/color/svg/1F612.svg',
    },
    {
        _id: '6096bf9fab2e797b569f4183',
        title: 'myGoodMood',
        image: 'https://openmoji.org/data/color/svg/1F604.svg',
    },
    {
        _id: '60af7f89d17994f991c5afc3',
        title: 'myNeutralMood',
        image: 'https://openmoji.org/data/color/svg/1F610.svg',
    },
] as const;
export type AllMoods = typeof allMoods[number]['image'];

export const allHobbies = [
    'apéro',
    'art',
    'arts du cirque',
    'arts martiaux',
    'astrologie',
    'astronomie',
    'basketball',
    'bilboquet',
    'chant',
    'cinéma',
    'concerts',
    'course à pied',
    'couture',
    'cuisine',
    'danse',
    'dessin',
    'développement personnel',
    'échecs',
    'ecologie',
    'écriture',
    'équitation',
    'escalade',
    'festivals',
    'films',
    'fitness',
    'football',
    'golf',
    'informatique',
    'jardinage',
    'jeux de société',
    'jeux vidéo',
    'kayak',
    'lecture',
    'mixologie',
    'musculation',
    'musique',
    'méditation',
    'natation',
    'netflix',
    'paintball',
    'peinture',
    'photographie',
    'plongée',
    'poterie - céramique',
    'poésie',
    'pâtisserie',
    'pêche',
    'randonnée',
    'skate',
    'snow / ski',
    'sport télévisé',
    'sports',
    'surf',
    'séries',
    'tennis',
    'théatre / improvisation',
    "tir à l'arc",
    'tricot',
    'voile',
    'volontariat',
    'voyages',
    'vélo',
    'web',
    'yoga',
] as const;
export type AllHobbies = typeof allHobbies[number];
