export const allMoods = [
    {
        _id: '6096bf96ab2e797b569f4182',
        title: 'mySadMood',
        image: 'https://openmoji.org/data/color/svg/1F612.svg',
    },
    {
        _id: '6096bf9fab2e797b569f4183',
        title: 'myGoodMood',
        image: 'https://openmoji.org/data/color/svg/1F604.svg',
    },
    {
        _id: '60af7f89d17994f991c5afc3',
        title: 'myNeutralMood',
        image: 'https://openmoji.org/data/color/svg/1F610.svg',
    },
] as const;
export type AllMoods = typeof allMoods[number]['image'];

export const allHobbies = [
    'sports',
    'lecture',
    'écriture',
    'développement personnel',
    'voyages',
    'astrologie',
    'randonnée',
    'yoga',
    'séries',
    'films',
    'regarder le sport à la TV',
    'volontariat',
    'jeux vidéo',
    'photographie',
    'tennis',
    'natation',
    'football',
    'surf',
    'théatre, improvisation',
    'snow - ski',
    'skate',
    'chanter',
    'couture',
    'plongée',
    'voile',
    'course',
    'escalade',
    'poterie - céramique',
    'peinture',
    'paintball',
    'musique',
    'mixologie',
    'méditation',
    'arts martiaux',
    'tricot',
    'kayak',
    'arts du cirque',
    'équitation',
    'golf',
    'jardinage',
    'pêche',
    'dessin',
    'danse',
    'cuisiner',
    'échecs',
    'musculation',
    'jeux de société',
    'vélo',
    'astronomie',
    "tir à l'arc",
    'poésie',
] as const;
export type AllHobbies = typeof allHobbies[number];
