name: test-ci
on:
  push:

jobs:
  test-front-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd Front && npm i && npm test